### ISSUE TITLE
cert-manager-webhook-dnsimple helm chart removal?

### ISSUE THREAD

**Issue by jasonadamyoung** [neoskop/helm-charts#1]
Hey Arne! 

I've been using your dnssimple hook for awhile for a hobby application. And noticed that my little hobby cluster started throwing errors this morning and traced it back to the removal of the helm chart in 871c5b790c6d7e980d91a75e58f6786df151c864

I can totally recreate that myself (and probably should to keep my dependencies in order), but just wondered if you've decided to stop maintaining that and why that changed ("No reason" is perfectly acceptable, it's totally your code and resources, and I completely understand)

Thanks!
Jason

**Comment by ShankyJS** [comment]
Ditto the question, what happened?

**Comment by moll-re** [comment]
Hello on behalf of Puzzle! The repository was migrated and along it the helm chart location. You should be able to deploy it using the helm repository under
https://puzzle.github.io/cert-manager-webhook-dnsimple

**Comment by ShankyJS** [comment]
Hey @moll-re, is the expectation to continue hosting this Helm Chart/Docker image for the long term while keeping it Open Source?

I think there's now a bunch of people that relay on this charts to be available and would love to know what are your plans for the long-term.

Thanks

**Comment by jasonadamyoung** [comment]
Thanks @moll-re! - I appreciate the followup.  

@ShankyJS - since this issue has a solution - I'm going to close out the issue. I think it's a fair and great question and would love to know myself. I'd encourage you to file it in the Puzzle repository for the webhook: https://github.com/puzzle/cert-manager-webhook-dnsimple/issues. 

@arnediekmann thanks so much for your work here - it's been a great help!  @moll-re and Puzzle team - thanks for continuing that work!

**Comment by arnediekmann** [comment]
@jasonadamyoung @ShankyJS Hey guys, sorry that I just reply now. I didn't see the issue here and honestly kind of forgot about the fact that this would cause problems for the existing users of the helm chart 😓 

@moll-re Thanks for pointing the new location out and thank you so much for taking over the project!
